version: '3' 

# Define the services/containers to be run
services:
  angular: 
    build:
      context: ./my-banking-app-frontend/
      dockerfile: Dockerfile
    ports:
      - "81:80" 
  
  express: 
    build:
      context: ./my-banking-app-backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    container_name: express-api
    links:
      - database

  database: 
    image: mongo 
    ports:
      - "27017:27017"   